### ISSUE TITLE
Request for Comments: Adding features which inspect and modify statuses

### ISSUE THREAD

**Issue by makimoto** [cookpad/expeditor#8]
For now users only can add events (success, failure and so on) to expeditor's services and see whether their circuit breaks are open or not.
However, in some cases, especially running test code, I want to inspect and modify statuses in expeditor's services. 

So I would like to add the following features to expeditor:

## 1. Accessor to the current status in services

I want to add a method `Expeditor::Service#current_status` which returns current `Expeditor::Status`.

```ruby
@service.current_status
# => #<Expeditor::Status:0x007fdeeeb18468 @break=0, @dependency=0, @failure=0, @rejection=0, @success=0, @timeout=0>
```

## 2. Status reset

A method to "reset" the service's status. A main use case may be before/after filter in test code like:

```ruby
describe '#something_with_exception'
  after do
    service.reset_status!
  end

  it 'does fallback' do
    expect(something_with_exception).to eq(default_value)
  end
end
```
  
## 3. Fallbackable flag

Most test cases do not want to take expeditor's circuit breaks into consideration.
So I want to introduce `Expeditor::Service#fallbackable` flag. If it is false, the fallback is disabled and exceptions in commands are raised .
It is set true as default and before a test case runs, it's turned to false and returned to true after the case finished.

---

@cookpad/dev-infra What do you think about it?
If my proposals are acceptable, I'll make pull reqs for each propose.

**Comment by k0kubun** [comment]
:+1: for these directions. But I felt "fallbackable" is not a proper expression since fallback itself is possible if it is configured. It's just disabled. So I propose "enable_fallback" or "fallback_enabled".

**Comment by makimoto** [comment]
@k0kubun 
"Enable_fallback" sounds good for me too. I'll use it.

**Comment by moro** [comment]
`fallback_enabled` sounds query method with `?` (`#fallback_enabled?`) but `enable_fallback` seems a "command" method which changes service status .

Does it fit your intention?

**Comment by makimoto** [comment]
I don't have strong opinions about "enable_fallback" or "fallback_enabled."
So I use "fallback_enabled."

**Comment by makimoto** [comment]
Thank you, all. I merged proposed features.
I'll make a new release including them as version 0.4.0.

**Comment by makimoto** [comment]
https://rubygems.org/gems/expeditor/versions/0.4.0
